import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Body, Container, Head, Heading, Html, Img, Preview, Section, Tailwind, Text, } from "@react-email/components";
import { emailTailwindConfig } from "../tailwind-config";
export const DokployBackupEmail = ({ type = "success", errorMessage, date = "2023-05-01T00:00:00.000Z", backupSize, }) => {
    const previewText = `Dokploy instance backup was ${type === "success" ? "successful ✅" : "failed ❌"}`;
    return (_jsxs(Html, { children: [_jsx(Preview, { children: previewText }), _jsxs(Tailwind, { config: emailTailwindConfig, children: [_jsx(Head, {}), _jsx(Body, { className: "bg-white my-auto mx-auto font-sans px-2", children: _jsxs(Container, { className: "border border-solid border-[#eaeaea] rounded-lg my-[40px] mx-auto p-[20px] max-w-[465px]", children: [_jsx(Section, { className: "mt-[32px]", children: _jsx(Img, { src: "https://raw.githubusercontent.com/Dokploy/dokploy/refs/heads/canary/apps/dokploy/logo.png", width: "100", height: "50", alt: "Dokploy", className: "my-0 mx-auto" }) }), _jsx(Heading, { className: "text-black text-[24px] font-normal text-center p-0 my-[30px] mx-0", children: "Dokploy Instance Backup" }), _jsx(Text, { className: "text-black text-[14px] leading-[24px]", children: "Hello," }), _jsxs(Text, { className: "text-black text-[14px] leading-[24px]", children: ["Your Dokploy instance backup was", " ", type === "success"
                                            ? "successful ✅"
                                            : "failed. Please check the error message below. ❌", "."] }), _jsxs(Section, { className: "flex text-black text-[14px] leading-[24px] bg-[#F4F4F5] rounded-lg p-2", children: [_jsx(Text, { className: "!leading-3 font-bold", children: "Details: " }), _jsxs(Text, { className: "!leading-3", children: ["Backup Type: ", _jsx("strong", { children: "Complete Dokploy Instance" })] }), _jsxs(Text, { className: "!leading-3", children: ["Content: ", _jsx("strong", { children: "/etc/dokploy + PostgreSQL Database" })] }), backupSize && (_jsxs(Text, { className: "!leading-3", children: ["Backup Size: ", _jsx("strong", { children: backupSize })] })), _jsxs(Text, { className: "!leading-3", children: ["Date: ", _jsx("strong", { children: date })] }), _jsxs(Text, { className: "!leading-3", children: ["Status:", " ", _jsx("strong", { children: type === "success" ? "Successful" : "Failed" })] })] }), type === "error" && errorMessage ? (_jsxs(Section, { className: "flex text-black text-[14px] mt-4 leading-[24px] bg-[#F4F4F5] rounded-lg p-2", children: [_jsx(Text, { className: "!leading-3 font-bold", children: "Reason: " }), _jsx(Text, { className: "text-[12px] leading-[24px]", children: errorMessage || "Error message not provided" })] })) : null] }) })] })] }));
};
export default DokployBackupEmail;
